# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.SlugField(help_text='What comes after the / in the URL. Keep it simple.Avoid spaces and special characters.', unique=True, verbose_name='Link Name')),
                ('destination_url', models.URLField(help_text='Where are you taking us?If it ends with # and then something,delete the # and everything after it.', max_length=2000, verbose_name='Destination URL')),
                ('campaign_medium', models.CharField(blank=True, choices=[('radio', 'Radio - On Air'), ('mailing', 'Mailing'), ('banner', 'Web Ad'), ('email', 'email'), ('social', 'social')], max_length=140, null=True, verbose_name='Primary Link Use')),
            ],
            options={
                'ordering': ['short_link'],
            },
        ),
    ]
